### ISSUE TITLE
After `mlaunch start`, while trying to connect to the launched instances, check to see if they're not running anymore

### ISSUE THREAD

**Issue by devkev** [rueckstiess/mtools#182]
This would be good when running a mongod with `--upgrade` (eg. downgrade 2.4 with text indexes to 2.2), where the mongod exits normally after doing the upgrade procedure, but without ever accepting connections.

**Comment by stennie** [comment]
`mlaunch` isn't aware of edge cases like `--upgrade` that might shutdown `mongod` after a period of initial processing. 

However, `mlaunch list` can be used  to check the current status of members of a deployment.

**Comment by p-mongo** [comment]
There may be another reason to check process status which is to reduce waiting time when the server unexpectedly dies (segfaults/exits due to configuration error). If mlaunch always only waits for server selection timeout, even if the entire deployment is dead it would still wait 30 seconds to tell the user it failed to provision.
