### ISSUE TITLE
Add mloginfo --queries support for aggregation queries

### ISSUE THREAD

**Issue by jonrangel** [rueckstiess/mtools#338]
Add support for cataloging distinct aggregation pipelines 'shapes' and aggregating count/min/max/avg runtime, just as for find() and update() operations.

**Comment by thechrisproject** [comment]
This would be great! I found while digging through some recent logs that our aggregate queries were the highest total time and had great variability. Having visibility via mloginfo would be fantastic.

**Comment by stennie** [comment]
Aggregation commands log a pipeline rather than a query pattern, so it isn't obvious how to create concise output that would be analogous to find or update queries with specific critieria. Pipelines can also be rewritten as a result of server [Pipeline Optimization](https://docs.mongodb.com/manual/core/aggregation-pipeline-optimization/).

However, `mloginfo --queries` does output stats for aggregate queries (count, min, max, etc) without trying to infer a pattern.

To investigate aggregation issues I'd suggest:

* use `mloginfo --queries` to identify potentially problematic aggregate commands

- use `mlogfilter` to extract log lines of interest (by namespace, duration, command, ...)
- use `mplotqueries` to explore the outliers in your filtered output

After reviewing available log information I'm going to close this as not viable for now, but please feel free to comment if you have suggestions on how to extract a meaningful summary.
