### ISSUE TITLE
--yaxis parameter not in help text

### ISSUE THREAD

**Issue by drmirror** [rueckstiess/mtools#347]
I'm using mtools 1.1.7 and the --yaxis parameter is not mentioned in the help text of mplotqueries.

**Comment by rueckstiess** [comment]
Yes thanks, that's correct but currently unavoidable. This is because `--yaxis` is an option that is only available for one particular type of plots, namely: `--type scatter` (which is the default). 

Current argument parsing implementation (everything is option with `--` prefix) doesn't allow for option-dependent arguments. 

Plan is to move all mtools scripts to a command based interface (think `git`). mlaunch is already like this:
```
mlaunch init
mlaunch start
mlaunch stop
mlaunch list
...
```
Each of these has its own arguments and options. 

#224 is the ticket to transition mloginfo to command-style. I will open one for mplotqueries as well and link here.

**Comment by rueckstiess** [comment]
In the mean time, I have to refer to the wiki for this: https://github.com/rueckstiess/mtools/wiki/mplotqueries#y-axis-value

**Comment by drmirror** [comment]
Understood, thanks. We figured it out by now, just thought it was an oversight.
