### ISSUE TITLE
"mlaunch nuke" which does "mlaunch kill --signal 9 && rm -rf $DATADIR"

### ISSUE THREAD

**Issue by devkev** [rueckstiess/mtools#362]
Asking the user `Are you sure? (y/N)` would probably be a good part of this.

I'm asking for this because I find myself doing it so often, and laziness is good.

If `nuke` is too colloquial, then something more boring like `destroy` or `wipe` would be alright too.  (`obliterate` would be a good non-boring option which is unfortunately way too much typing. :) )

**Comment by rueckstiess** [comment]
```
mlaunch cya
mlaunch bye
mlaunch astalavistababy
mlaunch boom
mlaunch terrrrrminate
```

**Comment by rueckstiess** [comment]
```
mlaunch itsnotyouitsme
```

**Comment by gianpaj** [comment]
```
mlaunch micdrop
```
:microphone: :boom: 

but seriously why not just:
```
mlaunch kill --force
or
mlaunch kill -9
```

**Comment by devkev** [comment]
Because that's only 3 characters shorter than what I currently type, which is
```
mlaunch kill
(wait a second or two)
rm -rf data
```
whereas `mlaunch nuke` is the same length as a plain `mlaunch kill`.

**Comment by gianpaj** [comment]
You can also have multiple paths for, e.g.
```
mlaunch {init,kill,start,stop} --dir data/sharded30wt
```

**Comment by rueckstiess** [comment]
Instead of adding a new command (feature creep *cough*), how about this:

```
mlaunch kill --delete
mlaunch kill -D
```

which does 2 things: 

1. it implies `--signal 9`   (because you don't care about the mongods anyway)
2. it deletes the data directory

I'd like to keep it a upper-case `D` (even though it is another key to press, sorry Kev), as a safety switch. 

Would that be acceptable for everyone? 

Do we need an `are you sure? y/N` because by that time you might as well just have typed `rm -rf data` instead...

**Comment by victorhooi** [comment]
I prefer `mlaunch nuke` (or `mlaunch <word>`) - I suspect it'll be more memorable (as well as harder to bork up) compared to remember different command flags.

**Comment by rueckstiess** [comment]
Given that there's a very simple workaround `mlaunch kill && rm -rf data`, which achieves the same outcome, I prefer not to add such convenience shortcuts which not only cost implementation, testing and documentation time but also ongoing maintenance.
