### ISSUE TITLE
mplotqueries not able to find matplotlib

### ISSUE THREAD

**Issue by andrewjamesmorgan** [rueckstiess/mtools#377]
Running on OSX. I've followed the instructions for installing all of the dependencies but I'm still seeing this error...

    Andrews-MBP-3:6.2 andrew$ mplotqueries filtered.log
    Traceback (most recent call last):
    File "/usr/local/bin/mplotqueries", line 9, in <module>
      load_entry_point('mtools==1.1.8', 'console_scripts', 'mplotqueries')()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
      return ep.load()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
      entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    File "/Library/Python/2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 26, in <module>
      raise ImportError("Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.")
    ImportError: Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.

Any suggestions?

Thanks, Andrew.

**Comment by rueckstiess** [comment]
Hi Andrew, 

This error often happens if you have several Python versions installed, and mtools uses a different one to where you installed matplotlib. 

Can you try the following from your shell prompt:

```
/usr/bin/env python -c "import matplotlib; print matplotlib.__version__"
```

Does this print out the matplotlib version number or raise an error that it can't find matplotlib? If it's an error, then your default Python does not have matplotlib installed.

**Comment by jmlrt** [comment]
Hi Thomas,
I have the same problem as Andrew on MacOS X 10.10.5:

````
[~/tmp/1]$ /usr/bin/env python --version
Python 2.7.10
[~/tmp/1]$ /usr/bin/env python -c "import matplotlib; print matplotlib.__version__"
1.4.3
[~/tmp/1]$ mplotqueries mongodb.log.1
Traceback (most recent call last):
  File "/usr/local/bin/mplotqueries", line 9, in <module>
    load_entry_point('mtools==1.1.8', 'console_scripts', 'mplotqueries')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 26, in <module>
    raise ImportError("Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.")
ImportError: Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.
```

**Comment by andrewjamesmorgan** [comment]
Seems to be installed ok…





Andrews-MBP:~ andrew$ /usr/bin/env python -c "import matplotlib; print matplotlib.__version__"

1.4.3







Thanks, Andrew.

**Comment by rueckstiess** [comment]
Sorry for the delay, but I think I finally may have found what the problem could be. It's (surprisingly) neither matplotlib nor mtools, but the `dateutil` package, that is acting up. Could you both please confirm the following: 

1\. This works without error:
```
 /usr/bin/env python -c "import matplotlib; print matplotlib.__version__"
```
2\. This one will fail
```
 /usr/bin/env python -c "import matplotlib.pyplot as plt"
```
probably with an error similar to this at the end:
```
  File "/Library/Python/2.7/site-packages/dateutil/rrule.py", line 16, in <module>
    from six.moves import _thread
```
3\. Your version of `python-dateutil` is > 2.2, likely 2.4.x. Check with `pip show python-dateutil`

If that is the case, then the following should fix the problem (see [this stackoverflow article](http://stackoverflow.com/questions/27630114/matplotlib-issue-on-os-x-importerror-cannot-import-name-thread)):

```
sudo pip uninstall python-dateutil
sudo pip install python-dateutil==2.2
```

My colleague ran into the same problem and downgrading python-dateutil to 2.2 solved it. I hope it will fix it for you, too. If you can let me know, I can pin the required version to 2.2 in mtools until the issue is fixed on their side.

**Comment by jmlrt** [comment]
Hi Thomas,
It's OK for me using python-dateutil==2.2.
Thank you for your help

**Comment by andrewjamesmorgan** [comment]
Works for me with python-dateutil==2.2 as well.

Thnaks :)
