### ISSUE TITLE
commandline histogram input with -b

### ISSUE THREAD

**Issue by jfcg** [rueckstiess/mtools#378]
mplotqueries --type histogram -b 1 mtools_filt.log
mplotqueries: error: argument logfile: can't open 1 as file or MongoDB connection string.

does not work but this does:

cat mtools_filt.log | mplotqueries --type histogram -b 1

i have 1.1.8 on ubuntu 14.04 64-bit

**Comment by rueckstiess** [comment]
Hi, yes this is a problem with the current command line interface. The individual plot types can add additional arguments, in this case, the "histogram" type adds the `-b` or `--bucketsize` parameter. Unfortunately, the top-level parser isn't aware of the additional argument and because it must consume one required argument (the filename) it uses the first it is unaware of: the `1`. 

To avoid this, you can either pipe the file in like you do, or you can put the filename at the first place directly after the command: 

```
mplotqueries mtools_filt.log --type histogram -b 1
```

This is a bit unusual for Linux users, who are used to adding the required argument last, but it gets around the issue. 

I've been meaning to make mplotqueries sub-command based, like for example git, see #348, which would fix the problem and make for a nice interface. The command would then become

```
mplotqueries histogram -b 1 mtools_fit.log
mplotqueries connchurn ...
mplotqueries scatter ...
```

Unfortunately I'm just a little short on time to introduce big changes like that.
