### ISSUE TITLE
kill/stop looks for .mlaunch_startup at wrong location

### ISSUE THREAD

**Issue by dotmanila** [rueckstiess/mtools#384]
```
[revin@acme mngo_3_0_6]$ pwd
/home/revin/msb/mngo_3_0_6
[revin@acme mngo_3_0_6]$ ls -alh
total 8.0K
drwxrwxr-x. 3 revin revin   43 Nov  6 21:56 .
drwxrwxr-x. 7 revin revin 4.0K Nov  6 19:36 ..
-rw-rw-r--. 1 revin revin 1.1K Nov  6 21:56 .mlaunch_startup
drwxrwxr-x. 4 revin revin   26 Nov  6 21:56 replset
[revin@acme mngo_3_0_6]$ mlaunch kill
can't read /home/revin/msb/mngo_3_0_6/data/.mlaunch_startup, use 'mlaunch init ...' first.
```

**Comment by dotmanila** [comment]
`--dir` solves the issue, but if its the same CWD, I think it should read there by default as well.

```
[revin@acme mngo_3_0_6]$ mlaunch kill --dir /home/revin/msb/mngo_3_0_6
sent signal 15 to 2 processes.
[revin@acme mngo_3_0_6]$```

**Comment by rueckstiess** [comment]
mlaunch assumes by default you're working in a parent directory of `./data` (the default value for `--dir`), and for easiest usage, you shouldn't set the `--dir` folder explicitly.

In your case, I would recommend you create `/home/revin/msb/mgo_3_0_6` manually, then from that directory you run `mlaunch init ...`. It will create a subfolder `./data` inside, and you can run `mlaunch start/stop/kill` from the folder `/home/revin/msb/mgo_3_0_6` without specificying `--dir`.

The reason is that mlaunch is primarily a tool for issue reproduction and testing, and you would often have many such environments/instances running simultaneously, possibly with other files related to that environment.
