### ISSUE TITLE
mlaunch version check fails silently and leads to unexpected side effects

### ISSUE THREAD

**Issue by vmenajr** [rueckstiess/mtools#451]
The version check fails for 2.6.12 and causes the LooseVersion compares to fail which then attempts to launch the config server with csrs

To repro:

```
mlaunch init --verbose --single --shards 1
creating directory: /home/vagrant/data/shard01/db
creating directory: /home/vagrant/data/configRepl/rs1/db
waiting for nodes to shutdown...
creating cluster without auth for setup, will enable auth at the end...
launching: mongod  --dbpath /home/vagrant/data/shard01/db --logpath /home/vagrant/data/shard01/mongod.log --port 27018 --logappend --fork  --shardsvr
launching: mongod --replSet configRepl --dbpath /home/vagrant/data/configRepl/rs1/db --logpath /home/vagrant/data/configRepl/rs1/mongod.log --port 27019 --logappend --fork  --configsvr
can't start process, return code 2. tried to launch: mongod --replSet configRepl --dbpath /home/vagrant/data/configRepl/rs1/db --logpath /home/vagrant/data/configRepl/rs1/mongod.log --port 27019 --logappend --fork  --configsvr
```

**Comment by JamesKovacs** [comment]
I found the same bug last night and was pointed to this bug with respect to 3.2.10. I investigated and the problem is how mlaunch parses out the version number from `mongod --version`. It takes the last 5 characters of the first line, which works fine for X.Y.Z version numbers where they are single digits. It fails for everything else. I am working on a PR to resolve this issue. Shouldn't take long to fix.

**Comment by vmenajr** [comment]
Hey @JamesKovacs.  Added the PR pretty much at the same time as the issue creation.
https://github.com/rueckstiess/mtools/pull/452

**Comment by JamesKovacs** [comment]
Awesome, @vmenajr. Pretty much the solution I had pseudo-coded in my head. Should have just written it rather than wasting time on sleep last night. :-P

**Comment by Steve-Hand** [comment]
It's probably not enough to simply derive "3.4.0-rc2" from "db version v3.4.0-rc2" because the LooseVersion implementation would not treat LooseVersion("3.4.0-rc2") and LooseVersion(""3.4.0") as equivalent, which is IMHO what you'd want. We need to hack off the training "-rc2" release candidate in order to have the needed equivalency.
