### ISSUE TITLE
Is mloginfo meant to work with mlogfilter output?

### ISSUE THREAD

**Issue by sommeric** [rueckstiess/mtools#573]
When mlogfilter is run on multiple files, it adds {filename} to the beginning of each line.  

{mongod.log} 2018-02-13T12:55:30.829+0200 I COMMAND [conn5] command test.$cmd command: profile { profile: 0.0, slowms: 100.0 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:43 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { W: 1 } } } protocol:op_command 0ms

This extra field throws off mloginfo's positional field assumptions.  Are they meant to work in tandem?  If so, mloginfo should recognize and ignore the filename or alternately, provide a command line option to ignore it.
 
### Environment

| Software         | Version
| ---------------- | -------
| mtools           |  1.3.2
| MongoDB server   |  3.2.10
| Operating system | OSX

**Comment by rueckstiess** [comment]
Also note: the "markers" that get prepended can be modified or turned off via a command line switch:
```
--markers [MARKERS [MARKERS ...]]
                        use markers when merging several files to distinguish
                        them. Choose from none, enum, alpha, filename
                        (default), or provide list.
```

**Comment by sommeric** [comment]
Yes, `--markers none` is a solution.  I checked, but overlooked this option.

If you think that mloginfo should auto-detect markers anyway, then you can leave this open as a feature request.  Otherwise, please close.

**Comment by rueckstiess** [comment]
It would be nice to auto-detect the markers, but it could potentially add significant parsing effort (in terms of performance). The current log parsing algorithm makes certain assumptions about how lines start (e.g. always with a timestamp, [code here](https://github.com/rueckstiess/mtools/blob/develop/mtools/util/logevent.py#L268)). I suspect adding additional checks to detect markers for each line would make it noticably slower. 

I'd be open to review a PR with some speed comparisons attached, but otherwise would close the issue now, since there's an easy workaround with `--markers none`.

**Comment by sommeric** [comment]
Closing.  Thanks again!
