### ISSUE TITLE
mlaunch: allow any number of arbiters

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#67]
`--arbiter` takes a number, default is 1, but can be anything.

**Comment by kevinadi** [comment]
I'm closing this issue with a couple of observations:

* We're not recommending more than 1 arbiter per replica set (https://docs.mongodb.com/manual/core/replica-set-arbiter/).
* Modifying this option will break the current convention, i.e. the `--arbiter` option is a boolean switch instead of requiring a number.
