### ISSUE TITLE
Publish dependency on psutil

### ISSUE THREAD

**Issue by jamesbroadhead** [rueckstiess/mtools#709]
`pip install mtools` does not install `psutil`, which is required.

**Comment by stennie** [comment]
@jamesbroadhead Since there are different dependencies depending on which scripts you want to run (for example, `psutil` is only required for `mlaunch`) the setup script treats those as optional. This decision was made early in mtools' life because extra dependencies can be more difficult to install on some platforms (particularly where a build toolchain is required).

You can install all dependencies with `pip install mtools[all]` or for specific tools by name (`pip install mtools[mlaunch,mloginfo]`):  http://blog.rueckstiess.com/mtools/install.html#dependencies

Regards,
Stennie

**Comment by stennie** [comment]
@jamesbroadhead I've hopefully made the optional dependencies more obvious in the [installation instructions](https://github.com/rueckstiess/mtools/blob/develop/doc/install.rst#installation-with-pip) on the `develop` branch.

Thanks,
Stennie
