### ISSUE TITLE
Confusing name, maybe rename the project to reflect it's for MongoDB

### ISSUE THREAD

**Issue by jschwartzenberg** [rueckstiess/mtools#814]
I am developing some Python tools to deal with DOS installation procedures. Some of the operations rely on a set of tools called mtools: https://en.wikipedia.org/wiki/Mtools
I searched online for Python bindings/implementations to avoid using `subprocess`.

### Expected behavior

I hoped to find information related to mtools and Python.

### Actual/current behavior

I found your project which seems to be about MongoDB tooling but is also called mtools :)

### Additional context

You may want to consider renaming as the mtools project is quite famous and using mtools in your name as well may not bring association with MongoDB for people familiar with the original mtools project.

**Comment by jschwartzenberg** [comment]
Hmm, I noticed this project is not that young either anymore. Not like the other one, but still. I can imagine you won't consider a rename at this point in time anymore as well.

**Comment by stennie** [comment]
Hi @jschwartzenberg,

The original author chose "mtools" when this project was created more than 7 years ago and the package name was unambiguous in the Python/PyPi namespace.  I don't think anyone would conflate this with DOS tools based on package descriptions and installation methods, but the naming of both projects is unfortunately generic.

The [GNU mtools](https://en.wikipedia.org/wiki/Mtools) project would be more accurately named "MS-DOS tools" and this project might be better as "MongoDB Tools". However, there is no central registry for globally unique open source project names and conflicts are inevitable.

If you search for open source `mtools` there are other projects like [mtools (Markup tools)](https://www.npmjs.com/package/mtools) on NPM, [mtools for Matlab](https://github.com/fnery/mtools), [mtools for multicast](https://github.com/troglobit/mtools), and even another Python-based [mtools (for sensing devices)](https://github.com/matthewwall/mtools).

Since there is established usage in the MongoDB community as well as [dependent projects](https://github.com/rueckstiess/mtools/network/dependents), I think it is too late to rename the existing mtools package on PyPi. Even if this package was renamed, it would be unexpected to reuse the PyPi namespace for an unrelated mtools package. However, if you are planning to develop open source Python wrappers for the DOS mtools, that would be a good opportunity to introduce a more suitable name for Python developers.

Regards,
Stennie
