### ISSUE TITLE
mloginfo show many versions, what does it mean?

### ISSUE THREAD

**Issue by rubdottocom-basetis** [rueckstiess/mtools#815]
When I execute mloginfo the output starts like:

```
     source: .\mongos.log.2020-07-13T10-16-18
       host: unknown
      start: 2020 Jun 27 09:12:03.598
        end: 2020 Jul 13 10:14:31.442
date format: iso8601-local
   timezone: UTC
     length: 218734
     binary: mongos
    version: 4.0.6 -> 1.0.2 -> 4.0.6 -> 1.0.2
    storage: unknown
```

What does it mean the version line?

`version: 4.0.6 -> 1.0.2 -> 4.0.6 -> 1.0.2`

I'm pretty sure that my mongo is at 4.0.6 version.

Commands are sent by NodeJS/Mongoose interface, I don't know it could have some relation with this.

Thank you

**Comment by stennie** [comment]
@rubdottocom-basetis `mloginfo` tries to detect multiple versions in log files (for example, if the server version was upgraded or multiple log files have been combined), but this appears to be a false report in your case.

You can ignore this detail since you know what version you are using, but to help fix the false positive it would be excellent if you can share the matching lines for: `grep "1.0.2" mongos.log.2020-07-13T10-16-18` (with any personally identifiable info redacted).

Thanks,
Stennie

**Comment by rubdottocom-basetis** [comment]
Thanks @stennie ,

Seems that the causing log line is:

`[mongosMain] OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017`
