### ISSUE TITLE
The provided mlogvis's  d3.js Javascript library link in the self-contained HTML file is no longer active

### ISSUE THREAD

**Issue by telenstanley** [rueckstiess/mtools#827]
### Environment

| Software         | Version
| ---------------- | -------
![image](https://user-images.githubusercontent.com/36274909/96374560-1084c980-1191-11eb-81fe-7d0e12d57100.png)

![image](https://user-images.githubusercontent.com/36274909/96374501-d0bde200-1190-11eb-9cbe-2b266284a550.png)

| mtools           | 1.6.4
| Python           | 3.9.0
| MongoDB server   |
| Operating system | windows 10

**Comment by stennie** [comment]
Hi @telenstanley,

`mlogvis` hasn't been actively updated since 2013 and has limited utility with modern MongoDB versions. It has been removed for the upcoming mtools 1.7.0 release.

Alternative options include `mplotqueries` or the [Free Monitoring](https://docs.mongodb.com/manual/administration/free-monitoring/) service available with MongoDB 4.0 or newer.

Regards,
Stennie
