### ISSUE TITLE
Issue with mismatch of mtools version and dateutils

### ISSUE THREAD

**Issue by thebionicman1** [rueckstiess/mtools#839]
### Expected behavior
The tool should find its dependencies in the directories provided.
### Actual/current behavior
It is not finding proper dateutils.
### Environment

scc897008> cat /etc/SuSE-release 
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 2

python --version
Python 3.6.3

ls **/nfs/disks/shahin_ad_20154002/pyBin/lib/python3.6//site-packages/**
UNKNOWN-0.0.0-py3.6.egg  mtools-1.6.4-py3.6.egg       psutil-0.7.0-py3.6-linux-x86_64.egg  python-dateutil-2.8.1
easy-install.pth         mtools-1.7.0.dev0-py3.6.egg  psutil-5.8.0-py3.6-linux-x86_64.egg**  python_dateutil-1.4-py3.6.egg

How do I make sure that my mtools + all other ones are aligned with my python versions?
The followings seems like to be expected and I do have them in my system
ordereddict>=1.1
**python-dateutil>=2.7**
matplotlib>=3.1.1
numpy>=1.16.4
pymongo>=3.9.0
psutil>=5.6.3,<5.7.0

| Software         | Version
| ---------------- | -------
| mtools           |
| Python           |
| MongoDB server   |
| Operating system |

**Comment by stennie** [comment]
Hi @thebionicman1,

Apologies this question was overlooked.

By default mtools tries to avoid installing extra dependencies since a few can be hasslesome to install in some environments.

You can find more information in the [mtools Installation](http://blog.rueckstiess.com/mtools/install.html#dependencies) documentation, but the TL;DR is that you can install all dependencies with:

> pip3 install mtools[all]

Or for the subset of scripts you use with:

> pip3 install mtools[mlaunch,mloginfo]

Regards,
Stennie
